[settings]
python.uv_venv_auto = true

[tools]
uv = "latest"

[tasks.lint]
depends = ["lint:format", "lint:code"]

[tasks."lint:format"]
run = "uv run ruff format --check ."

[tasks."lint:code"]
run = "uv run ruff check ."

